# -*- coding: utf-8 -*-
"""data_question_answer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F4_Rl828-aJqnVF0NbSJZwrI-buhUyPB
"""

# !pip install openai
# !openai migrate

import pandas as pd
from openai import OpenAI
import numpy as np
'''
# df = pd.read_csv('/content/content2.csv').drop(columns=['Id'])
# df = df.dropna().reset_index().drop(columns=['index'])
# for i in range(14244):
#   if len(df['Content_'][i]) < 100 :
#     df.drop([i],inplace=True)
# df = df.drop_duplicates(subset=['Content_'])
# df = df.reset_index().drop(columns=['index'])
# df['QA1'] = np.nan
# df['QA2'] = np.nan
# df['QA3'] = np.nan
# df.to_csv('content2.csv')
'''

df = pd.read_csv('df200.csv')
client = OpenAI(api_key=open('api.txt','r').read().strip('\n'))

content = "از متن زیر 3 سوال همراه با جواب طرح کن. سوالات را در فرمت زیر قرار بده:سوال:پاسخ:سوال:پاسخ:سوال:پاسخ:"

for i in range(875,1500):
  try: 
    Content = content + df['Content_'][i]
    print(i)
    # print(Content)
    completion = client.chat.completions.create(model = 'gpt-3.5-turbo',messages = [{ "role":"user" , 'content':Content}])
    QA = completion.choices[0].message.content.split('\n\n')


    df['QA1'][i] = QA[0]
    df['QA2'][i] = QA[1]
    df['QA3'][i] = QA[2]
  except:
    print(Exception)
    df.to_csv('df300.csv')
    break
df.to_csv('df300.csv')
